ARG SERVICE

# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM node:22-alpine AS builder
ARG SERVICE

WORKDIR /app

COPY services/${SERVICE}/package*.json ./
RUN npm ci
COPY services/${SERVICE} .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/dist dist/
#COPY --from=builder /app/node_modules node_modules/
#COPY package.json .
EXPOSE 3000
#ENV NODE_ENV=production
#CMD [ "node", "build" ]